### ISSUE TITLE
Can't test the online classify of LeNet in python/tutorials/mnist.ipynb

### ISSUE THREAD

**Issue by DamonDeng** [dmlc/mxnet-notebooks#19]
Found that the sample python/tutorials/mnist.ipynb include codes of MLP and LeNet, while the model of LeNet can't be used in the HTML online classify cell.

I would like to suggest that we can create two mnist demo, one is basic and the other one is advance.

In the basic one , say mnist_basic.ipynb, we can demo the MLP network with CPU, in the advice one , say mnist_advance.ipynb, we can demo the LeNet network with GPU.

If it is OK, I will create a pull request for that .  Looking forward to your response.

**Comment by mli** [comment]
the lenet model rewrite `mod`, so we can reuse the previous HTML box to test it. there is no necessary to have another box. i added a comment block in the notebook to explain it.
